In [1]:
import torch

In [2]:
tensor = torch.tensor([[1,2,3],[4,5,6]],dtype=int,device='cpu')
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [3]:
torch.zeros(size= (3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.arange(start=1,end=10,step=2)

tensor([1, 3, 5, 7, 9])

In [5]:
torch.empty(size=(2,5)).normal_(mean=0,std=2)

tensor([[-2.2695, -3.1011, -2.6930,  0.1077,  1.2508],
        [-2.5004, -2.5018, -3.7270,  0.1241,  1.1981]])

Convert tensors to other data type

In [6]:
x = torch.arange(4)
x.bool()

tensor([False,  True,  True,  True])

In [7]:
x.short() #int16

tensor([0, 1, 2, 3], dtype=torch.int16)

In [8]:
x.long()

tensor([0, 1, 2, 3])

In [9]:
x.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

Array and Tensor interconversion

In [10]:
import numpy as np
arr = np.array([[1,3,4],[2,3,2]])
tensor = torch.from_numpy(arr)
tensor

tensor([[1, 3, 4],
        [2, 3, 2]])

In [11]:
arr_back = tensor.numpy()
arr_back

array([[1, 3, 4],
       [2, 3, 2]])

Tensor math

In [14]:
x= torch.tensor([1,3,8])
y= torch.tensor([-7,6,5])

#Addition
z1 = torch.empty(3)
torch.add(x,y,out= z1)
z = x+ y 

z = x- y 

# division 
z = torch.true_divide(x,y) # divides element by element and if y is int '2' then each element of x by 2

#inplace operation
x.add_(y) # makes changes in x
x += y # x = x+y would make a copy 

#Exponentiation
z = x.pow(2)
z = x **2

# Simple Comparision
z = x > 0 # z will be a boolean tensor

# Matrix Multiplication and ops 

x1 = torch.rand((2,5))
x2 = torch.rand((5,1))

x3 = torch.mm(x1,x2)
x3 = x1.mm(x2)

#x1.matrix_power(3) for square matrices

#element wise multiplication
z = x*y

# dot product
z = torch.dot(x,y)

# batch matrix multiply
tensor1 = torch.rand((32,10,20))
tensor2 = torch.rand((32,20,30))

multi = torch.bmm(tensor1,tensor2)

Broadcasting

In [21]:
x1 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x2 = torch.tensor([[2,1,2]])
z = x1 + x2
z2 = x1 ** x2
print(x1)
print(x2)
print(z)
print(z2)


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[2, 1, 2]])
tensor([[ 3,  3,  5],
        [ 6,  6,  8],
        [ 9,  9, 11]])
tensor([[ 1,  2,  9],
        [16,  5, 36],
        [49,  8, 81]])


other useful ops


In [ ]:
x = torch.arange(5)

z = torch.clamp(x,min = 0, max = 10 ) # outside the range replaced by max minima


TENSOR INDEXING

In [27]:
data_size = 10
features = 8

x =torch.rand((data_size,features),)

x[0,:] # first row
x[:,2] # 3rd column
x[2,0:5]

x[3,4] = 97 

# fancy indexing 
x2 = torch.arange(10)

index = [1,3,4]
x2[index]

#Conditional 
#x[(x<2 | x> 8 )] 

z = torch.where(x>5,x,x*2) # (condition , output(if condition true),output(if condition false))

